### ISSUE TITLE
Query about the Feature names

### ISSUE THREAD

**Issue by sonnylaskar** [Far0n/xgbfi#4]
Hello,
Thanks for sharing your work.
I was just exploring it and I got confused in one area.

My data has features named v1, v2, v3, ...
I build a feature map and the xgb.dump.

In the excel report, the interaction columns contains f2|f3, f10|f11, etc.
Do I need to manually map these names to the actual variables names.

Or am I doing something wrong.
Please comment.

**Comment by Far0n** [comment]
The feature names in the excel should match the ones in die feature map. A manual mapping is not necessary, if the feature map has been correctly created and passed to the dump function:
`gbdt.dump_model('xgb.dump', fmap='xgb.fmap', with_stats=True)`.

**Comment by sonnylaskar** [comment]
Thanks Far0n.
I had a mistake with the R code for feature map. I figured it out.
I had to spend some time to read about how to create the map in R. Below is the code is used:

```
featureList <- names(train.x) # Change train.x as desired
featureVector <- c() 
for (i in 1:length(featureList)) { 
  featureVector[i] <- paste(i-1, featureList[i], "q", sep="\t") 
}

write.table(featureVector, "fmap.txt", row.names=FALSE, quote = FALSE, col.names = FALSE)
xgb.dump(model = bst, fname = 'xgb.dump', fmap = "fmap.txt", with.stats = TRUE)

```
