### ISSUE TITLE
how to build project in VS?

### ISSUE THREAD

**Issue by duthchao** [Far0n/xgbfi#5]
Hi,Far0n:
      Sorry for disturbing you.I am a newer to C#.When put this project in My VS2015,choose release and build.Some errors occur!

**Error CS0246  The type or namespace name 'SplitValueHistogram' could not be found (are you missing a using directive or an assembly reference?)   XgbFeatureInteractions  
Severity    Code    Description Project File    Line    Suppression State
Error   CS0246  The type or namespace name 'SplitValueHistogram' could not be found (are you missing a using directive or an assembly reference?)   XgbFeatureInteractions**    

how to solve this problem?

**Comment by Far0n** [comment]
plz try again. should be fixed now. :)

**Comment by duthchao** [comment]
OK,thank you,My problem have been solved!
You are so generous to providing this genius tool！

**Comment by Far0n** [comment]
you are welcome :)
